export const theme = {
  colors: {
    black: '#000',
    white: '#fff',
    text: '#2a2a2a',
    background: '#E5EBF3',
    backgroundSecondary: '#fafcff',
    primary: '#07c',
    secondary: '#89898f',
    accent: '#07BAD2',
    muted: '#f6f6f6',
    borderColor: '#E5EBF3',
    title: '#747578',
    online: '#28de37',
    offline: '#f5341b',
    backgroundTable: '#EAF2F2',
  },
  space: [0, 2, 4, 8, 16, 32, 48, 64, 128, 256],
  fonts: {
    body: 'Open Sans, system-ui, sans-serif',
    heading: 'Roboto, system-ui, sans-serif',
    monospace: 'Menlo, monospace',
  },
  fontSizes: {
    xs: '12px',
    s: '14px',
    m: '16px',
    l: '24px',
    xl: '32px',
  },
  fontWeights: {
    normal: 400,
    medium: 500,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  borders: {
    none: 'none',
    normal: '1px solid',
  },
  radii: {
    none: '0',
    normal: '4px',
    roundedSquere: '10px',
    round: '50%',
  },
};
